### ISSUE TITLE
[ng] date-select - open on a certain date

### ISSUE THREAD

**Issue by lucienbertin** [LuccaSA/lucca-front#1027]
when the date-select opens its picker, the calendar is centered around today, it would be a plus to add an input if we want to specify a specific date around which initializing the calendar

use-case figgo
we are arond may 2020, its a restricted period until june if you want to declare a leave of absence. as a result we would like the calendar to open on july, cuz its the first month after the current restricted period

**Comment by sanlucca** [comment]
Others are asking for that, we need to reprioritize it
