### ISSUE TITLE
actionIcon misalignment

### ISSUE THREAD

**Issue by pjerem** [LuccaSA/lucca-front#1081]
Hello,

It looks like the icons in actionIcon buttons are not centered anymore since the new icon pack. (Firefox 78.0.2 (64 bits) Windows)

It can be seen here : http://prisme.lucca.io/components/actions/action-icons

![image](https://user-images.githubusercontent.com/72425/87675967-50927580-c778-11ea-9a9e-5523d3a0cf4c.png)

👋

**Comment by sanlucca** [comment]
Fixed with the new actionIcons :)
