### ISSUE TITLE
Default side-nav color

### ISSUE THREAD

**Issue by bastienguillon** [LuccaSA/lucca-front#1084]
Why is the default side-nav color hard coded ? The palette could be used here as well

https://github.com/LuccaSA/lucca-front/blob/9069e926a2d83ab447a151f179ea27636d1f5ba4/packages/scss/src/theming/components/_nav-side.theme.scss#L4

**Comment by sanlucca** [comment]
Nope, we realised that in Design we use a specific color for the sideNav background, therefore we do not add another palette just for that
