### ISSUE TITLE
Disabled is-success buttons

### ISSUE THREAD

**Issue by bastienguillon** [LuccaSA/lucca-front#1131]
Buttons with the `is-success` class are not supposed to be clickable: they end up being disabled most of the time. However, the combo `button.is-success:disabled` produces a button with a low opacity

![image](https://user-images.githubusercontent.com/8553617/92950789-95c3e280-f45d-11ea-99ca-14e84f33d2af.png)

I think it would look better with a `100%` opacity

![image](https://user-images.githubusercontent.com/8553617/92950869-ba1fbf00-f45d-11ea-8659-61dd18945d6e.png)

**Comment by lucienbertin** [comment]
i believe `button.is-success`  have a pointer-event: none, so you shouldn't need to mark it disable

or am i missing the point ?

**Comment by bastienguillon** [comment]
> i believe button.is-success have a pointer-event: none, so you shouldn't need to mark it disable

Indeed, nevermind then
