### ISSUE TITLE
Input clearer changes input size

### ISSUE THREAD

**Issue by sanlucca** [LuccaSA/lucca-front#1133]
![image](https://user-images.githubusercontent.com/26228000/93075371-fdf50d00-f685-11ea-82b7-b52b0d675729.png)
![image](https://user-images.githubusercontent.com/26228000/93075389-03525780-f686-11ea-90c3-3535f31cbdd5.png)

**Comment by BertrandPodevin** [comment]
@sanlucca i can't seems to be able to reproduce. Is this issue is already fixed or is there some specific condition to for it to occur?
