### ISSUE TITLE
[API Select] It should allow both "Multiple" mods

### ISSUE THREAD

**Issue by sanlucca** [LuccaSA/lucca-front#1134]
We can't currently choose between "Show all value" or "show count" mods for API Select Multiple mod.

**Comment by lucienbertin** [comment]
you can provide your own displayer if you want

```html
<!-- will display [12] elements -->
<lu-api-select multiple api="/some/api/of/things"></lu-api-select>
<!-- will display 12 times the span -->
<lu-api-select multiple api="/some/api/of/things">
  <span class="chip" *luDisplayer="let thing">{{ thing.dongle }}</span>
</lu-api-select>
```

**Comment by lucienbertin** [comment]
i dont know if it answers your question. but we try to stay coherent between the api-select, user-select, and department-select which have a "`12` users" kind of displayer
