### ISSUE TITLE
Proposal: UiStateModule

### ISSUE THREAD

**Issue by GuillaumeNury** [LuccaSA/lucca-front#1166]
When we deal with asynchronous actions, we often have to add some loaders. Sometimes, we even want to add a success or error state to our buttons.
This is a proposal, implemented in PM, that could be added in LF.

## UiState

Instead of representing loaders with a boolean, I introduced a new `Enum`:

```ts
export enum UiState {
  Idle,
  Loading,
  Success,
  Error,
}
``` 

## UiStateDirective

This directive is just a way to add LF classes based on input `UiState`:
```ts
@Directive({
  selector: '[pmUiState]'
})
export class UiStateDirective {
  @HostBinding('class.is-loading')
  public get isLoading(): boolean {
    return this.state === UiState.Loading;
  }

  @HostBinding('class.is-success')
  public get isSuccess(): boolean {
    return this.state === UiState.Success;
  }

  @HostBinding('class.is-error')
  public get isError(): boolean {
    return this.state === UiState.Error;
  }

  @Input('pmUiState') public state: UiState;
}
```

## RxJS `onUiStateChange` operator

The goal is to achieve the orchestration of `UiStates`:

* Loading -> Success (1 second) -> Idle
* Loading -> Error (1 second) -> Idle

Here is an example:

```ts
export class ExportFeature {
  public generateExportReportState$: BehaviorSubject<UiState>;

  protected constructor() {
    this.generateExportReportState$ = new BehaviorSubject(UiState.Idle);
  }

  public generateExportReport(): void {
    this.getExportReport()
      .pipe(
        onUiStateChange(state => this.generateExportReportState$.next(state)),
      )
      .subscribe(
         report => { /* some thing with this.getExportReport() result */},
         err => { /* some thing with this.getExportReport() error */}
       );
  }
}
```

Implemented [HERE](https://github.com/LuccaSA/Pay.Monitor/blob/5ebc98df6ac3fd9c9635934c89c6dcb39b831a03/front/src/app/utils/rxjs.ts#L11) and tested [HERE](https://github.com/LuccaSA/Pay.Monitor/blob/5ebc98df6ac3fd9c9635934c89c6dcb39b831a03/front/src/app/utils/rxjs.spec.ts#L8).

**Comment by sanlucca** [comment]
@lucienbertin what's your take on that ?

**Comment by Supamiu** [comment]
@GuillaumeNury Do we want to follow this path or should we just close the issue?

**Comment by GuillaumeNury** [comment]
I'd like to add this in LF as it is copy-pasted in many projects

**Comment by GuillaumeNury** [comment]
Added in @lucca/cdk
