### ISSUE TITLE
fullTemplateTypeCheck and strictTemplates

### ISSUE THREAD

**Issue by GuillaumeNury** [LuccaSA/lucca-front#1181]
When using LF with fullTemplateTypeCheck and strictTemplates, we have a bunch of errors when using
- `<lu-user-tile />`
- ` | luUserDisplay`

Because they expect a `ILuUser`. The thing is that they work with only a `firstName` and a `lastName`. We could use `Partial<ILuUser>` or a new type.

**Comment by lucienbertin** [comment]
luUserDisplay wont work without a firstName or lastName

**Comment by GuillaumeNury** [comment]
I had to use a [hack](https://github.com/LuccaSA/Pay.Monitor/blob/d3366f93830cfb4cb6115332faaf8e9f64292913/front/src/app/pipes/lu-user-pipe/lu-user.pipe.ts). 

You cannot use `<lu-user-tile />` with a slightly different interface:
```ts
export interface PayUser {
    readonly id?: number;
    readonly firstName?: string | null;
    readonly lastName?: string | null;
    readonly employeeNumber?: string | null;
}

export interface ILuUser {
    id: number;
    firstName: string;
    lastName: string;
    picture?: {
        href: string;
    };
    jobTitle?: string;
    additionalInformation?: string;
}
```

**Comment by lucienbertin** [comment]
why is your user having a `readonly` `optional` `firstName` ?

anyway, the `luUserDisplay` wont work without a firstname/lastname, so i'm pretty ok with it throwing an error at compile time in your use case

**Comment by GuillaumeNury** [comment]
Ok, after digging further, our user interface had only optional fields. After fixing nswag, it works like a charm !
