### ISSUE TITLE
use CSS custom properties to reduce dist size

### ISSUE THREAD

**Issue by BertrandPodevin** [LuccaSA/lucca-front#1183]
As of today, color-palette definitions on CSS elements take up to 38% of the size of LF dist.

This is due to usage of loop when defining palette.

Here's a simplified example of how colors palettes are currently defined on elements :
```
.element {
	[..]
	@each $name, $palette in _getMap("palettes") {
		&.palette-#{$name} {
			color: _color($palette);
			background: _color($palette, "600");
		}
	}
}
```
which translate to :

```
.element.palette-error {
	color: xxxxxx;
	background: xxxxxx;
}
.element.palette-warning {
	color: xxxxxx;
	background: xxxxxx;
}
.element.palette-palette-success {
	color: xxxxxx;
	background: xxxxxx;
}
.element.palette-palette-primary {
	color: xxxxxx;
	background: xxxxxx;
}
.element.palette-palette-secondary {
	color: xxxxxx;
	background: xxxxxx;
}
```
To avoid this heavy redundancy, we could instead use CSS custom properties like this :

First define palettes colors with custom properties on `:root` level. This is done once and for all and will work for every element.
```
.palette-success {
	--color: xxxxxx;
	[...]
	--c600: xxxxxx;
	[...]
}
.palette-warning {
	--color: xxxxxx;
	[...]
	--c600: xxxxxx;
	[...]
}
[...]
```

And then replace the css loop on the element with :
```
.element {
	&[class*="palette"] {
		color: var(--color);
		background-color: var(--c600);
	}
}
```

which translate to :

```
.element[class*="palette"] {
	color: var(--color);
	background-color: var(--c600);
}
```

_Note : the `[class*="palette"]` is not mandatory and could be dropped but is here to keep the same specificity as before and avoid side effects._

For this simple example this is an approx. gain of 75% in size. 

We could also consider to apply this method for the sizes modificators (mod-label-shorter, mod-label-short...)

Of course, this optimization could only be considered **after the end of IE11 support**

**Comment by jeremie-lucca** [comment]
Done in LF10
