### ISSUE TITLE
State management for form fields

### ISSUE THREAD

**Issue by vvalentin-lucca** [LuccaSA/lucca-front#1201]
We want to be able to browse the required fields without getting an error:

- we don't want errors when ng-invalid and ng-touched are enabled;
- we want errors when ng-invalid, ng-touched and ng-dirty are enabled.

**Comment by lucienbertin** [comment]
i'm really not sure it's a good idea

**Comment by jeremie-lucca** [comment]
Guidelines were provided. Still in discussion. I'm closing it for now.
