### ISSUE TITLE
chip multiline

### ISSUE THREAD

**Issue by lucienbertin** [LuccaSA/lucca-front#1237]
![image](https://user-images.githubusercontent.com/10089239/106896458-de708680-66f1-11eb-87e2-00d6cbdf65dd.png)

its white on almost white, but the chips `presentation   (x)` that seem to bug have a long text that gets broken into 2-3 lines

![image](https://user-images.githubusercontent.com/10089239/106896641-24c5e580-66f2-11eb-8980-9fec9100fd7c.png)

**Comment by BertrandPodevin** [comment]
There are 2 ways to fix this bug, both with pro and con :

-> Use ellipsis, visually better but with informations loss
![image](https://user-images.githubusercontent.com/65592565/109327564-c3101b80-7858-11eb-94e0-81d2e3bb4401.png)

-> Using word-break and auto height. No information loss, better for accessibility but visually not that great and hyphen may be a bit random for longs words.

![image](https://user-images.githubusercontent.com/65592565/109327655-dde29000-7858-11eb-81c8-53cb1faa72bd.png)

![image](https://user-images.githubusercontent.com/65592565/109328103-5c3f3200-7859-11eb-9963-f3b5e3de6901.png)

**Comment by lucienbertin** [comment]
i prefer ellipsis. if you want to write war and peace, dont put it in a `chip`

**Comment by BertrandPodevin** [comment]
Taking the picture provided with this issue as an example, using ellispis could be a little confusing
![ex](https://user-images.githubusercontent.com/65592565/109470793-2de76f80-7a70-11eb-9391-4a87fe18434a.jpg)

**Comment by lucienbertin** [comment]
i'm okay with this

the way i understand chips and their usage, they shouldn't impact your layout by suddenly taking 3 lines. so a chip _should_ stay on one line. 

in the above example, what is there to force 2 chips per line minimum, if you remove it you'll have something like

`Presentation customer success`
`Presentation des channels`
`Parteniares lucca` `Presentation timmi`
`presentation des outils` `presentation UX`
...

and you can have the best of both worlds
- you have the length of the container to display as much info as poissible
- you stay on one line making the layout easy

**Comment by lucienbertin** [comment]
also, in all the work nolwenn and you did on the rework of select-multiple, chips always stay on one line

https://www.figma.com/file/lS1IRgPwCVdstwzpJINC7x/S%C3%A9lection-multiple-%5BGUILDE%5D?node-id=177%3A6684

imagine this, but some chips can take 3 lines

![image](https://user-images.githubusercontent.com/10089239/109472692-bff07780-7a72-11eb-8001-43d8c5ef80a6.png)
