### ISSUE TITLE
Remove the overlay from the select?

### ISSUE THREAD

**Issue by vvalentin-lucca** [LuccaSA/lucca-front#1302]
When a select is open, the overlay blocks access to the help tooltip.

![Capture d’écran 2021-05-03 à 16 26 06](https://user-images.githubusercontent.com/64789527/116888891-4456a680-ac2c-11eb-96e1-7de13e74cfce.png)

**Comment by lucienbertin** [comment]
if we do that, i dont know how to handle closing the picker via click outside

**Comment by jeremie-lucca** [comment]
Frames fields are now deprecated.
