### ISSUE TITLE
ets-select - better display for small tenants

### ISSUE THREAD

**Issue by lucienbertin** [LuccaSA/lucca-front#1318]
in teh ets-select the grouping by LU is not necessarily super usefull for most of our tenants cuz its only usefull when you have a lot of ets and LU

if we look at the stats we have (\*)

| condition | % of tenants |
| :--- | ---: |
| just 1 ets | 40% |
| less than 6 ets | 80% |
| just 1 LU | 70% |
| etsCnt == luCnt | 55% |
| 2 LU or more && 6 ets or more | 10 % |

the current group by LU display is really usefull only in the last case, so for 10% of our tenants

so we could, when opening the picker, fetch the number of ets and LU (2 http get that should resolve quickly) and use it to choose if we want to group by LU or even if the LU name carries some relevant information

we already swap between a display grouped by LU and not grouped by LU when searching, we just need to plug 2 new booleans into this
 
> \* remember that these stats are *per tenant* but the component is consummed by *end users*. we can/could weight each tenant by its user base size. my gut feeling is that big fat tenants with lots of users are the 10% tenants with lots of LU and Ets ; so the 10% teant stat might look bad but could translate to 40-60% of users

**Comment by lucienbertin** [comment]
needs to check that the 2 http get calls that i want to run at onOpen are indeed fast

**Comment by celiancailler** [comment]
ticket lié sur le hub 
https://luccasoftware.atlassian.net/browse/HUB-3353

**Comment by lucienbertin** [comment]
english plz
