### ISSUE TITLE
[DS to LF] Dropdown : Element search

### ISSUE THREAD

**Issue by AlexiaAlarza** [LuccaSA/lucca-front#1339]
- [ ] Separate component for forms
- [ ] Create a separate style + document dropdowns

![Capture d’écran 2021-05-26 à 17 14 58](https://user-images.githubusercontent.com/77682210/119685735-eb061f80-be45-11eb-866d-2693847fb727.png)

**Comment by jeremie-lucca** [comment]
Redesigned as material style is deprecated and available :)
