### ISSUE TITLE
[DS to LF] Dropdown : Element text

### ISSUE THREAD

**Issue by AlexiaAlarza** [LuccaSA/lucca-front#1340]
- [ ] Use only the secondary palette
- [ ] create is-error
- [ ] Document on Prisme

![Capture d’écran 2021-05-26 à 17 17 07](https://user-images.githubusercontent.com/77682210/119686232-6bc51b80-be46-11eb-9162-ae8b0dfb9465.png)

**Comment by jeremie-lucca** [comment]
Up to date
