### ISSUE TITLE
[DS to LF] Dropdown : Element checkbox

### ISSUE THREAD

**Issue by AlexiaAlarza** [LuccaSA/lucca-front#1341]
- [ ] Use only the secondary palette
- [ ] Document on Prisme

![Capture d’écran 2021-05-26 à 17 19 43](https://user-images.githubusercontent.com/77682210/119686389-944d1580-be46-11eb-8844-54d6f024ae4d.png)

**Comment by jeremie-lucca** [comment]
Up to date
