### ISSUE TITLE
[DS to LF] Data tables : Head

### ISSUE THREAD

**Issue by AlexiaAlarza** [LuccaSA/lucca-front#1345]
- [ ] add mod-borderTop
- [ ] change padding top & bottom
- [ ] use grey600 for text
- [ ] padding right 0 for checkbox
- [ ] add Prisme documentation for the head filters

![Capture d’écran 2021-05-26 à 17 27 43](https://user-images.githubusercontent.com/77682210/119687699-b2674580-be47-11eb-88fb-9ea998d6fbbf.png)

**Comment by jeremie-lucca** [comment]
I'm closing it now as tables are going to be redesigned in next quarters.
