### ISSUE TITLE
[DS to LF] Data tables : Cell

### ISSUE THREAD

**Issue by AlexiaAlarza** [LuccaSA/lucca-front#1346]
- [ ] Checkbox : padding right 0px 
- [ ] Cells on 2 lines (2 colors on table-body)
- [ ] Team (cf avatars) 
- [ ] Icon in grey-600 
- [ ] Textfield small width

![Capture d’écran 2021-05-26 à 17 30 22](https://user-images.githubusercontent.com/77682210/119688203-112cbf00-be48-11eb-9f6e-f991ac5564f8.png)

**Comment by jeremie-lucca** [comment]
I'm closing it now as tables are going to be redesigned on next quarters.
