### ISSUE TITLE
[DS to LF] Data tables : Table group

### ISSUE THREAD

**Issue by AlexiaAlarza** [LuccaSA/lucca-front#1347]
- [x] change expand/collapse icon
- [x] remove underline on hover and use background grey100 + text grey800 for the whole line

![Capture d’écran 2021-05-26 à 17 31 35](https://user-images.githubusercontent.com/77682210/119688408-40433080-be48-11eb-9a92-24b569a74dcf.png)

**Comment by jeremie-lucca** [comment]
Done
