### ISSUE TITLE
[DS to LF] Messages : Toast

### ISSUE THREAD

**Issue by AlexiaAlarza** [LuccaSA/lucca-front#1349]
- [ ] Add palettes
- [ ] Put the title in block to make the content go underneath
- [ ] Plan with an icon
- [ ] Change default background + palette to 800
- [ ] Fix toasts-item-kill position. Should be right - top, not right - center

![Capture d’écran 2021-05-26 à 17 33 44](https://user-images.githubusercontent.com/77682210/119688733-89938000-be48-11eb-8fe6-e88299372994.png)

**Comment by jeremie-lucca** [comment]
Fixed by https://github.com/LuccaSA/lucca-front/pull/1971
