### ISSUE TITLE
[DS to LF] Avatars

### ISSUE THREAD

**Issue by AlexiaAlarza** [LuccaSA/lucca-front#1351]
- [x] Review existing sizes
- [x] Plan a mod-icon
- [ ] Team (several avatars cf timmi & poplee) on figma that on the elements of tables perhaps to foresee alone also?
- [x] Bonus : Passer les background images en image (@GuillaumeNury)

![Capture d’écran 2021-05-26 à 17 35 34](https://user-images.githubusercontent.com/77682210/119689004-ca8b9480-be48-11eb-93b5-6806d37f6a37.png)

**Comment by GuillaumeNury** [comment]
**Petite explication à propos des `background-image` pour les photos utilisateurs**

On a pas mal d'interfaces qui affichent des listes d'utilisateurs, potentiellement assez longues. Ainsi, on demande d'un coup un grand nombre d'images au serveur alors qu'elles ne sont pas forcément toutes visibles à l'écran.

Sur les balises `img`, il est possible de mettre l'attribut `loading="lazy"` qui permet de ne charger l'image qu'au moment ou celle-ci est visible à l'écran.

Pour se rendre compte du volume d'appels que ça représente, il y a eu plus de 37 millions d'appels de fichier en juillet 2022 !

**Comment by jeremie-lucca** [comment]
Done. Except for multiple avatar which have a dedicated issue : https://github.com/LuccaSA/lucca-front/issues/2036
