### ISSUE TITLE
[DS to LF] Dialogs : Modal

### ISSUE THREAD

**Issue by AlexiaAlarza** [LuccaSA/lucca-front#1354]
- [ ] Border to add in the header
- [ ] Box-shadow on the footer
- [ ] Padding to review
- [ ] Add new modal sizes
- [ ] Focus state on the cross
- [ ] Mobile version to manage
- [ ] Bonus : Add an `outline: none;` to `lu-modal-header` to avoid displaying focus style on some conditions (like open modal, push tab, close modal, open modal again. See screen bellow)

![Capture d’écran 2021-05-26 à 17 40 07](https://user-images.githubusercontent.com/77682210/119689778-6ddca980-be49-11eb-83ba-85007978f0e7.png)

<img width="722" alt="image" src="https://user-images.githubusercontent.com/25581936/182378452-fc137198-be7e-460d-9b53-59436ca4337f.png">

**Comment by Ptit-Biscuit** [comment]
Salut,
J'allais ouvrir une nouvelle issue mais visiblement celle-ci contient déjà le todo :)

Avec @BertrandPodevin on a remarqué que le focus n'était pas le bon à l'ouverture d'une modale, du coup on peut spammer un bouton et ouvrir X modales superposées.
Après de multiples essaies il faudrait 'simplement' ajouté un `tabindex="0"` sur l'élément portant les attributs `cdkTrapFocus` et `cdkTrapFocusAutoCapture` (cf. https://github.com/LuccaSA/lucca-front/blob/v7.0.3/packages/ng/modal/src/lib/modal-panel.component.html#L1) comme ça le focus se fait bien dans la modale.

Un point que je comprends pas cependant c'est que la doc angular material indique qu'il existe des attributs `cdkFocusRegionStart` et `cdkFocusRegionEnd` qui permettraient de vraiment limiter les tab à l'intérieur de la modale mais j'ai jamais réussi à les faire fonctionner ...

**Comment by jeremie-lucca** [comment]
Cover fixed footer 
![image](https://user-images.githubusercontent.com/25581936/188899018-7124187e-b224-4e22-ba87-41e7991e909c.png)
