### ISSUE TITLE
[DS to LF] Dialogs : Sidepanel

### ISSUE THREAD

**Issue by AlexiaAlarza** [LuccaSA/lucca-front#1355]
- [x] Border to add in the header
- [x] Box-shadow on the footer
- [x] Padding to review
- [x] Add new modal sizes
- [x] Focus state on the cross
- [ ] Check responsive with size mods

![Capture d’écran 2021-05-26 à 17 41 52](https://user-images.githubusercontent.com/77682210/119690163-bc8a4380-be49-11eb-87fd-8f045003d7bb.png)

**Comment by jeremie-lucca** [comment]
Review SP size after https://github.com/LuccaSA/lucca-front/issues/2045
