### ISSUE TITLE
[DS to LF] Forms : Filled

### ISSUE THREAD

**Issue by AlexiaAlarza** [LuccaSA/lucca-front#1359]
- [x] Set the icon to 600 (except disabled)
- [x] 3 sizes mod-small etc.
- [x] Double palette to manage
- [x] Text & placeholder colors according to states
- [x] Icon colors
- [x] Cross icon to manage (date, select, search)
- [x] Look at size helper message
- [x] By default primary => 2 palettes (default, error) attention disabled is in grey

![Capture d’écran 2021-05-26 à 17 48 44](https://user-images.githubusercontent.com/77682210/119691159-a2049a00-be4a-11eb-85bf-db315e0eab83.png)

**Comment by jeremie-lucca** [comment]
Everything seems ok with news _textField_ component ✌️
