### ISSUE TITLE
postinstall dont work on macs

### ISSUE THREAD

**Issue by lucienbertin** [LuccaSA/lucca-front#1384]
cuz we need to do a npm link in the postinstall script, but for macos we need elevated privileges

workaround for now :

after running npm ci locally, do the linkage manually
```
sudo npm link --prefix packages/icons
sudo npm link --prefix packages/scss
sudo npm link @lucca-front/scss @lucca-front/icons
```

**Comment by jeremie-lucca** [comment]
Done
