### ISSUE TITLE
[sass] math.div instead of /

### ISSUE THREAD

**Issue by lucienbertin** [LuccaSA/lucca-front#1396]
sass v 1.33 introduces operator math.div

https://sass-lang.com/documentation/breaking-changes/slash-div

but we cant yet migrate to it because

- angular 12.0.3 still uses sass 1.32 and i'm not sure i can go over ng 12.0.3 because nexst patch broke my integration with storybook (see commit d1a0fcc and this issue https://github.com/storybookjs/storybook/issues/15227)
- angular 12.1 uses sass 1.33+
- LF 7.0 must be retro compatible with ng 11

but we can prepare for the migration by
- using the right version in the local env when storybook + ng 12 issue is fixed
- reference sass >1.33 in package/sccs peer dep in next major/minor
- act on a depreciation plan

**Comment by jeremie-lucca** [comment]
Done
