### ISSUE TITLE
Decreasing chained pseudoselectors specificity

### ISSUE THREAD

**Issue by sanlucca** [LuccaSA/lucca-front#1455]
Pseudoselectors shouldn't be chained like that: 
![image](https://user-images.githubusercontent.com/26228000/135624593-c46a3bc8-ab44-4075-9e93-c9983b5d2c5d.png)

They should be written using this syntax: `:pseudoselector(selector1, selector2, ...)`

**Comment by jeremie-lucca** [comment]
Already fixed: https://github.com/LuccaSA/lucca-front/blob/master/packages/scss/src/components/inputs/field/_field.framed.scss#L38
