### ISSUE TITLE
Lu-select items alignment

### ISSUE THREAD

**Issue by BertrandPodevin** [LuccaSA/lucca-front#1463]
The alignments of items in lu-select aren't great, especialy with (but not restricted to) `mod-small`
![image](https://user-images.githubusercontent.com/65592565/137156835-eac63245-330f-4711-8756-da1a4275e515.png)

Instead of abitrary absolute positionings and line-heights we should only use flex `align-items: center` for this

**Comment by jeremie-lucca** [comment]
Partially fixed. Replaced by https://github.com/LuccaSA/lucca-front/issues/2348
