### ISSUE TITLE
Refactor color management

### ISSUE THREAD

**Issue by MarcFairbrother** [LuccaSA/lucca-front#1465]
Legacy colors need to be removed from LF and color management could be simplified:

- replace `white` with `#FFFFFF` or `_color("grey", 0)`
- pass palette values as numbers istead of strings
- replace `background` with `background-color` when setting a color
- `_color("text.default")` is replaced with `_color("grey")`
- `_color("text.light")` is replaced with `_color("grey", 500)`
- `_color("text.placeholder")` is replaced with `_color("grey", 400)`
- `.u-textDefault` is replaced  with `.u-grey` and/or `.u-grey700`
- `.u-textLight` is replaced with `.u-grey500`
- `.u-textPlaceholder` is replaced with `.u-grey400`
- `black` and `#121212` should be removed
- all colors are defined by their 6 character hexadecimal code
- all colors should refer to variables declared in the palettes
- the 700 value is set as the `_color` function's default 
- the 700 value should not be passed to the color function
- `map $colors` should be removed from the code base
- the palette's `text` value should be renamed `contrast` or `inverted`
- components  in the scss and ng packages need to be updated
- a migration guide will be necessary to manage the update and breaking changes
- update default colors
- replace sass color functions with calls to palette colors

## Specific to Lucca Softs

- only primary and secondary palettes should have overrides

**Comment by jeremie-lucca** [comment]
Is currently deeply redesigned with color tokens.
