### ISSUE TITLE
Date picker hide label in mod framed

### ISSUE THREAD

**Issue by vvalentin-lucca** [LuccaSA/lucca-front#1469]
Date inputs in framed mode have their labels hidden when the calendar is displayed.

![2021-10-21 11 25 51](https://user-images.githubusercontent.com/64789527/138250240-abf8542c-40e1-4c5b-a167-4c8b9c9bb5bb.gif)

**Comment by jeremie-lucca** [comment]
Frame mod are now deprecated.
