### ISSUE TITLE
[NG] Infinite loader on selects when source is synchronous

### ISSUE THREAD

**Issue by GuillaumeNury** [LuccaSA/lucca-front#1485]
![image](https://user-images.githubusercontent.com/12662533/143568641-41206d96-08cd-49eb-aeaf-ab432bc7a3e1.png)

**How to reproduce:**

```ts
@Injectable()
export class MyApiService extends ALuApiService {
    //...
	searchAll(clue: string, filters: string[] = []): Observable<T[]> {
		return of([{ id: 1, name: 'Test' }]);
	}

	searchPaged(clue: string, page: number, filters: string[] = []): Observable<T[]> {
		return of([{ id: 1, name: 'Test' }]);
	}
}

```

**Why:**
There is a racing condition between `results$` and `query$` in [api-searcher.model.ts](https://github.dev/LuccaSA/lucca-front/blob/d568005455762c2330f5d3d3b4f8d598e4c34c7a/packages/ng/api/src/lib/select/searcher/api-searcher.model.ts#L117).

**Comment by Supamiu** [comment]
This issue is specific to the deprecated selects, closing in favor of the new selects.
