### ISSUE TITLE
User tile use word-break: break-all on name

### ISSUE THREAD

**Issue by BertrandPodevin** [LuccaSA/lucca-front#1489]
The user tile component set a `word-break: break-all;` on `user.info`. This properties should never be used because it's 1) super ugly and 2) a cheap way to manage overflow

![image](https://user-images.githubusercontent.com/65592565/144583645-be8d1bd3-d1b1-4419-92a1-97ec2a543001.png)

**Comment by jeremie-lucca** [comment]
Right, but we have to deal with specific cases like emails
