### ISSUE TITLE
Disabled color on lu-date-select

### ISSUE THREAD

**Issue by AlexiaAlarza** [LuccaSA/lucca-front#1506]
Fix color on disabled placeholder and disabled color on commons file

![Capture d’écran 2022-01-11 à 15 25 28](https://user-images.githubusercontent.com/77682210/148961469-77e12c8c-a316-4567-b090-4474af8ea5e1.png)
![Capture d’écran 2022-01-11 à 15 25 13](https://user-images.githubusercontent.com/77682210/148961473-2b586393-e66f-4ea3-937f-7c5b0b064394.png)
![Capture d’écran 2022-01-11 à 15 23 29](https://user-images.githubusercontent.com/77682210/148961478-992b09b2-c905-4ed7-9713-7ab358897141.png)

**Comment by jeremie-lucca** [comment]
Already fixed
<img width="230" alt="image" src="https://github.com/LuccaSA/lucca-front/assets/25581936/73c5eb9e-6f77-49dc-b9e4-de5cca898c24">
