### ISSUE TITLE
Links underlining

### ISSUE THREAD

**Issue by bpaugam** [LuccaSA/lucca-front#155]
`mod-link` on a button gives it a regular hyperlink look.

Problem is, I find that the spacing between text and underline is way too tight by default. I'd rather give it some extra space.

This could be achieved this way (that also prevents us from having to make the button relatively positioned):

https://codepen.io/benoitpaugam/pen/xPPzOr

This example also shows that sometimes, I would like a decorative element (the "+" sign here) not to be underlined. Which would be perfectly doable.

**Comment by lucienbertin** [comment]
@jeremie-lucca is it fixed with  #358
