### ISSUE TITLE
[Table] Keyboard and action icons

### ISSUE THREAD

**Issue by jeremie-lucca** [LuccaSA/lucca-front#1557]
Actions are not visible on table line focus.

**Comment by almonais** [comment]
add .actionButton on button who are not an .actionIcon
.table-body-row:hover .table-body-row-cell.mod-actions .actionIcon,
.table-body-row:focus .table-body-row-cell.mod-actions .actionIcon,
.table-body-row:focus .table-body-row-cell.mod-actions .actionButton,
.table-body-row:focus-within .table-body-row-cell.mod-actions .actionIcon,
.table-body-row:focus-within .table-body-row-cell.mod-actions .actionButton {
  opacity: 1;
}

**Comment by jeremie-lucca** [comment]
Done https://github.com/LuccaSA/lucca-front/pull/1561
