### ISSUE TITLE
Feature request => Color picker

### ISSUE THREAD

**Issue by F2X** [LuccaSA/lucca-front#1567]
Today we have some weird/inconsistent rendering on `input type="color"` in forms, maybe we can do something about it.

see @bastienguillon for more details

**Comment by GuillaumeNury** [comment]
We also have an implementation in [Timmi Office](https://github.com/LuccaSA/Figgo.Flex/blob/main/front/src/app/pages/settings/pages/work-locations/components/form/work-location-form.component.html#L17) using a regular popover

**Comment by jeremie-lucca** [comment]
👉 [Roadmap DS](https://www.notion.so/3aaa62d8cf2d4023b98982d087233557?v=3adc750d99c844b9985285d5e4d8f3b0)
