### ISSUE TITLE
[callout] .link in callout do not use current color

### ISSUE THREAD

**Issue by BertrandPodevin** [LuccaSA/lucca-front#1618]
Any `a` or element  with a `.link` class (ex `button`) inserted in a .callout.palette-X no longer inherit current color

![image](https://user-images.githubusercontent.com/65592565/164470802-753e552c-8e74-4a2f-8488-9bfff3175bd2.png)

**Comment by jeremie-lucca** [comment]
@BertrandPodevin The link issue will be fixed on 8.2 : https://github.com/LuccaSA/lucca-front/issues/1569
But it supports only `<a>` element (with `.link` or not).
Do you have a specific need for `<button>` ?

**Comment by BertrandPodevin** [comment]
@jeremie-lucca yes my specific need is a for `button.link`. 

By the way i think that there is a bug in https://github.com/LuccaSA/lucca-front/pull/1572 : in `callout.scss` `a` color has been changed from `inherit` to `grey800`. With color override removed from the mixin `calloutDefaultPalette` i dont think that link color (`a` or `.link`) in a `callout` + `palette-x` work anymore

**Comment by jeremie-lucca** [comment]
Fixed by https://github.com/LuccaSA/lucca-front/pull/1633 in 8.2
