### ISSUE TITLE
[MENU] Wrong items spacing when using legacy syntax

### ISSUE THREAD

**Issue by BertrandPodevin** [LuccaSA/lucca-front#1619]
When using legacy syntax on `menu`, the space between items is twice as long as normal. 

That's because `.menu` now have a` spacings.big` `gap` wich add to the existing `margin-right` of `.menu-link`.

**Comment by jeremie-lucca** [comment]
Fixed (8.1.5) https://github.com/LuccaSA/lucca-front/pull/1629
