### ISSUE TITLE
[Button group] button group + palette do not have the correct color separator

### ISSUE THREAD

**Issue by BertrandPodevin** [LuccaSA/lucca-front#1622]
They are currently white, they should be in their respective color palette 900 :

**Currently**

![image](https://user-images.githubusercontent.com/65592565/164500989-149e1a2f-c71e-4ff8-a4b6-79a1d062acfd.png)

------------------------------------------------------------------
**Design system :**

![image](https://user-images.githubusercontent.com/65592565/164500914-a2f4c6cb-ee51-45be-a5be-5c373f352472.png)

**Comment by jeremie-lucca** [comment]
Canceled for now after discussions with design team
