### ISSUE TITLE
[lu-department-select] Dropdown's direction the first time it is opened

### ISSUE THREAD

**Issue by bastienguillon** [LuccaSA/lucca-front#1637]
The `lu-department-select` dropdown does not seem to be opened in the right direction the first time it is opened. Here is an example where the dropdown's direction is Down even though it should have been Up :

https://user-images.githubusercontent.com/8553617/165918259-8844c703-4802-4c71-ae1a-d9108fde4a3c.mp4

My guess is that the component does not know if the data which will be displayed will fit, so it chooses the Down direction by default

**Comment by bastienguillon** [comment]
It seems to be specific to the `lu-department-select` component, the `lu-user-select` has the right behavior for example:

![image](https://user-images.githubusercontent.com/8553617/165921582-47385df3-65ee-4bc0-8e96-55eb0da53a91.png)

**Comment by jeremie-lucca** [comment]
Tested recently and could not reproduce.
I guess recent fix on luSelect fixed the issue : https://github.com/LuccaSA/lucca-front/pull/2764


https://github.com/LuccaSA/lucca-front/assets/25581936/ac089b85-3c4a-4605-b8a6-9aabb0f0eddf
