### ISSUE TITLE
Utility .u-fontWeightRegular is missing

### ISSUE THREAD

**Issue by jeremie-lucca** [LuccaSA/lucca-front#1813]
Also, to discuss :
Should we remove `u-fontWeight400/600` and only keep `u-fontWeightRegular/Bold`?

**Comment by jeremie-lucca** [comment]
Discuss it with @vvalentin-lucca

**Comment by vvalentin-lucca** [comment]
Two ideas here: 

1. stick to the same naming logic of atomic classes (`u-propertyAndValueInCamelCase` like `u-displayFlex`);
2. avoid confusion between keywords and numbers to define text weights.

Numbers | Keywords
-- | --
100 | Ultra-light, Extra-light
200 | Light, Thin
300 | Book
400 | Regular, Normal
500 | Medium
600 | Semibold, Demibold
700 | Bold
800 | Heavy, Black, Extra-bold
900 | Ultra-black, Extra-black, Fat, Poster

(We had a u-fontWeightBold that was loading semi-bold incorrectly until now.)

I wouldn't worry about it:

```
.u-fontWeight400,
.u-fontWeightNormal,
.u-fontWeightRegular {
	font-weight: 400;
}

.u-fontWeight600,
.u-fontWeightSemiBold,
.u-fontWeightDemiBold {
	font-weight: 600;
}
```

But maybe it's easier to all agree on the values in numbers right?
