### ISSUE TITLE
Bug Tooltips with LF 10.0

### ISSUE THREAD

**Issue by almonais** [LuccaSA/lucca-front#1824]
probleme with import 
  --components-tooltip-background-color: var(--palettes-secondary-text);
  --components-tooltip-color: var(--colors-white-color);

and font-size actually is a line-height and not a font-size, and it's bigger
.mat-tooltip {
  font-size: var(--sizes-smaller-font-size) !important;
}

**Comment by jeremie-lucca** [comment]
@almonais The font size will be fixed. Can you detail the color issue? It seems fine on my side 🤔 

`--components-tooltip-background-color: var(--palettes-grey-900);
--components-tooltip-color: var(--colors-white-color);`
