### ISSUE TITLE
[ActionIcon] do not use their own defined default-palette

### ISSUE THREAD

**Issue by BertrandPodevin** [LuccaSA/lucca-front#1854]
In LF10 actionIcons have a defined `default-palette` (wich is `primary` but should probably be `grey`) but do not use it afterward, simply using directly the `grey` palette instead.

![image](https://user-images.githubusercontent.com/65592565/190126254-3680d69a-eec0-4c67-87a2-cd6b2cc19a13.png)

**Comment by jeremie-lucca** [comment]
https://github.com/LuccaSA/lucca-front/issues/1854

**Comment by GuillaumeNury** [comment]
Fixed by #2069
