### ISSUE TITLE
[Propostion] Gestion des styles scopés dans LF

### ISSUE THREAD

**Issue by lfaldalucca** [LuccaSA/lucca-front#1872]
L'appli mobile Timmi Temps/Absences/Office est une sorte de "portail" avec 3 "sous-appli" qui, dans un premier temps, vont toutes avoir leur thème de couleurs
Malheureusement à l'heure actuelle LF ne répond pas à ce cas de figure, en effet certains trucs ne sont pas scopés :
- les variables de couleurs etc. sont dans le :root
- certaines éléments de base, type liens <a> ont du style générique, dont certaines couleurs
- dans les composants, on rajoute des variables sur :root également avec les @at-root
Certes on peut redéfinir les palettes mais on ne peut pas vraiment les redéfinir pour un élement enfant de root car il se passe ceci :
```scss
:root {
  --red: red;
  --autreVariable: var(--red);
}
.timmi-timesheet {
  --red: blue;
  * {
    color: var(--autreVariable) !important; // donne du rouge
  }
}
```

ca fait une espèce de closure en quelque sorte

on a le cas de figure par exemple pour les var css du spinner de chargement, qui font référence à palettes-primary-200 et palettes-primary-700 : 

```scss
// commons/config.scss
$loading: (
	'background': var(--palettes-primary-200),
	'frontground': var(--palettes-primary-700),
	'speed': 600ms,
);
```

cette map est ensuite utilisée dans un sélecteur :root :
```scss
// commons/base.scss
:root {
	[...]
	@include core.cssvars('commons-loading', config.$loading);
        [...]
```

On pourra redéfinir autant que l'on veut les palettes dans un  élément descendant de :root, --commons-loading-background fera toujours référence à la variable scss "de :root", qui n'est pas overridée.
Un solution serait donc de redéfinir également --commons-loading-background dans l'élement descendant de :root sur lequel on a redéfinit les palettes, introduisant une notion de "scope" pour les déclarations de variables

**Comment by GuillaumeNury** [comment]
@lfaldalucca is it ok with #1874 ? Can we close this issue ?

**Comment by lfaldalucca** [comment]
> @lfaldalucca is it ok with #1874 ? Can we close this issue ?

👍
