### ISSUE TITLE
[Form Framed] radiosfield radiosfield-input - the gap spacing is too large 

### ISSUE THREAD

**Issue by RipripKipkip** [LuccaSA/lucca-front#1878]
`.form.mod-framed .radiosfield .radiosfield-input`
![image](https://user-images.githubusercontent.com/30234402/193758308-77670448-b41f-4e6e-90f3-d9db8292ab59.png)

**Currently:**
`gap: var(--components-field-horizontal-spacing); (1.5rem)`
`gap: 1.5rem;`

**Proposal:**
`gap: var(--components-field-vertical-spacing) var(--components-field-horizontal-spacing);`
`gap: .25rem 1.5rem;`

**Comment by jeremie-lucca** [comment]
Documentation issue
