### ISSUE TITLE
add a "Today" button in the calendar

### ISSUE THREAD

**Issue by DavidBenazra** [LuccaSA/lucca-front#1890]
This "today" button is available  in Timmi-Timesheet on the iOS application and Desktop version but not in PWA.
It would be useful when navigating too far in time and you just want to go back to "Today" for imputation or anything else

**Comment by jeremie-lucca** [comment]
It seems that some standard practices are : 
- Displaying a "today" button to navigate on a calendar vue (not a picker) 
- Displaying a "today" button to pick current day on a datepicker : https://ant.design/components/date-picker/

It need to be discussed with Clément

**Comment by jeremie-lucca** [comment]
Transfered to insights
