### ISSUE TITLE
[Status] states ans palettes management is unconsistent with others components

### ISSUE THREAD

**Issue by BertrandPodevin** [LuccaSA/lucca-front#1902]
The way our new status component handle palettes and states is unconsistent with the other LS components.

- States are named `error`, `warning` and `success`. They should be named `is-error`, `is-warning` and `is-success`
- Dot color is managed with a `u-textXXX` on the `status-dot` element. It shoud be a `palette-XXX` on the `status` element.

**Comment by jeremie-lucca** [comment]
It seems to be already fixed. 
Also, the component is deprecated and replaced by Status Badge.
