### ISSUE TITLE
[button] mod-white incompatible with palettes

### ISSUE THREAD

**Issue by BertrandPodevin** [LuccaSA/lucca-front#1929]
`button.mod-white` box-shadow color is hardcoded (primary-500) and doesn't work with `palettes`.
![image](https://user-images.githubusercontent.com/65592565/206141843-af751794-9c65-48b3-ae81-da5c80ff0e04.png)

It should be fixed : there are cases where we need a `mod-white + palette` :
![image](https://user-images.githubusercontent.com/65592565/206142031-29f95b8d-bd3c-4c9f-ace8-5bb2a2e214ae.png)

**Comment by jeremie-lucca** [comment]
Seems already fixed
![image](https://user-images.githubusercontent.com/25581936/229080224-b94bbebd-c0b2-48b0-a38a-2661bfd8fb27.png)
