### ISSUE TITLE
[Fields -> textfields / radiosfields / checkboxesfields] bugs & side effects

### ISSUE THREAD

**Issue by BertrandPodevin** [LuccaSA/lucca-front#1941]
Fields -> textfields / radiosfields / checkboxesfields mecanism is currently bugged at mutliples levels and should be overhauled.

A few examples :

- Radiosfield getting a `--components-textfield` background. Luckily this doesn't works ether because of css vars component encapsulation

![image](https://user-images.githubusercontent.com/65592565/209158683-3298827c-5f89-4051-9690-c9510722787e.png)

- Radiosfield impacting textfield-label

![image](https://user-images.githubusercontent.com/65592565/209159218-fb58a81b-cd01-4365-9353-2136b73a72ec.png)

![image](https://user-images.githubusercontent.com/65592565/209159082-2d12468a-68fb-4065-a1f2-83698b5df8ed.png)

**Comment by jeremie-lucca** [comment]
These fields are now deprecated.
New form fields have dedicated classes / vars.
