### ISSUE TITLE
[Sidepanels] structure is broken

### ISSUE THREAD

**Issue by BertrandPodevin** [LuccaSA/lucca-front#1942]
Sidepanels now have a `div[role="document"]` between `lu-sidepanel-panel` and` lu-modal-header / content / footer.
`

This new `div` break the `flex` `lu-sidepanel-panel` inheritance, with side effects.

Ex `lu-modal-footer` no longer beeing at the bottom.

![image](https://user-images.githubusercontent.com/65592565/209166406-e814f380-e341-46e6-b777-195a20782231.png)

![image](https://user-images.githubusercontent.com/65592565/209166303-3a435983-c737-4398-9df8-5406dbbcfe2b.png)

**Comment by jeremie-lucca** [comment]
https://github.com/LuccaSA/lucca-front/pull/1945#pullrequestreview-1230113118
