### ISSUE TITLE
[Avatar] Multiple

### ISSUE THREAD

**Issue by jeremie-lucca** [LuccaSA/lucca-front#2036]
Add a wrapper for multiple avatars.

![Capture d’écran 2023-03-09 à 16 45 29](https://user-images.githubusercontent.com/25581936/224079507-c1b3e050-1c04-4689-a558-4168f4b3b26e.png)

**Comment by vvalentin-lucca** [comment]
Some tests here too: https://codepen.io/vincent-valentin/pen/eYrEGed
