### ISSUE TITLE
[EmptyState] new mod ? creation of a mod in line

### ISSUE THREAD

**Issue by RipripKipkip** [LuccaSA/lucca-front#2042]
## Description
Currently we have empty state column style while we also have empty line style

### Currently example:
![image](https://user-images.githubusercontent.com/30234402/224710546-4080e8a2-8b12-41ab-824a-5a7986d13e90.png)

### New Design example:
Cleemy Paiements
![image](https://user-images.githubusercontent.com/30234402/224710412-711ebdfc-a545-46d6-975f-6e6df10937e8.png)
Timmi Timesheets
![image](https://user-images.githubusercontent.com/30234402/224709848-7f91bbfd-0d87-4968-8ef7-513693a1ca83.png)
Timmi Office
![image](https://user-images.githubusercontent.com/30234402/224727241-d0f706aa-528c-40fa-b6de-45733275bc6e.png)

**Comment by jeremie-lucca** [comment]
Empty state was redesigned and a new component will be released in january https://github.com/LuccaSA/lucca-front/pull/2369
