### ISSUE TITLE
[RadioButtons] add mod-counter

### ISSUE THREAD

**Issue by RipripKipkip** [LuccaSA/lucca-front#2071]
A counter mode is missing
![image](https://user-images.githubusercontent.com/30234402/229445751-5e686bcb-80f1-4458-bcdf-4d70249094cb.png)

[Figma](https://www.figma.com/file/sO3msermeMuyFvUAcXrbn5/Main-Components-2.0?node-id=3082%3A1418&t=Ig5StTZk79MYjMVN-1)

```
.radioButtons {
  &.mod-counter {
    .radioButtons-item-label {
      display: flex;
      align-items: center;
      gap: var(--spacings-XS);
    }
  }
}
```
Results :
![image](https://user-images.githubusercontent.com/30234402/229445829-9c276283-0e57-4b61-a400-5ad6ebf0302b.png)

**Comment by jeremie-lucca** [comment]
Done thanks to numericBadge : https://lucca-front.lucca.io/storybook/?path=/docs/qa-forms-radiobuttons--docs
