### ISSUE TITLE
[Rich text] New component

### ISSUE THREAD

**Issue by jeremie-lucca** [LuccaSA/lucca-front#2087]
<img width="523" alt="image" src="https://user-images.githubusercontent.com/25581936/233010144-6e9869e9-8e39-4991-a6c4-d2d628f98756.png">

https://www.figma.com/file/PQEOcUF9CYfKNqaejAGLWP/Lucca-components?node-id=6946%3A36388&t=aRm0NWNIlJXE0i3X-1

**Comment by GuillaumeNury** [comment]
All teams use QuillJS to handle these. Could we provide just a theme? It's not easy to code from scratch

**Comment by jeremie-lucca** [comment]
👉 [Roadmap DS](https://www.notion.so/3aaa62d8cf2d4023b98982d087233557?v=3adc750d99c844b9985285d5e4d8f3b0)
