### ISSUE TITLE
LuUserPicture - add a directive [picture-size] that can be used ito display bigger images 

### ISSUE THREAD

**Issue by fiorila** [LuccaSA/lucca-front#209]
For the moment we have LuUserPictureComponent that resizes images with a width of 100px . But sometimes  we need to display bigger images, so we can let the choice to developper to set the size: `<lu-user-tile [user]="user" [picture-size]="200">`

**Comment by lucienbertin** [comment]
yeah, no. the picture is called with ?width=100 but it doesnt work for picture hosted bty anything other than lucca, also it's bugged

i removed the `width=100` i think. if you wanna display it larger, use a css override and you're golden

**Comment by jefBinomed** [comment]
fix by https://github.com/LuccaSA/lucca-front/commit/131458ca3335490f99ef834c5e52ca313ed7a40d
