### ISSUE TITLE
[Utilities] - u-flexOrder1, u-borderRadius & u-overflowAuto

### ISSUE THREAD

**Issue by nsarradin** [LuccaSA/lucca-front#2125]
- Unlike what is mentioned in https://prisme.lucca.io/94310e217/p/21a286-utilitaires, the u-flexOrder1 class doesn't exist in LF
- the !important mention is missing on u-borderRadius classes

**Comment by jeremie-lucca** [comment]
`u-overflowAuto` is also required by Talent
