### ISSUE TITLE
[Toast] Bottom offset & footer

### ISSUE THREAD

**Issue by jeremie-lucca** [LuccaSA/lucca-front#2131]
Add offset with bottom positioning if page has a footer.

![capture_d___e__cran_2023-06-02_a___18 20 07](https://github.com/LuccaSA/lucca-front/assets/25581936/df7f85b5-a2c1-4f00-a155-acc20b92278a)

**Comment by lvoirin** [comment]
@jeremie-lucca Comment on vote pour une issue ? 😁 
On a ce problème qui commence à prendre des proportions importantes avec notre nouveau footer des feuilles de temps 😬 

https://github.com/LuccaSA/lucca-front/assets/121884900/e7a191b6-2863-4829-80ce-9db025e0c534

**Comment by lvoirin** [comment]
@RipripKipkip 🥳
