### ISSUE TITLE
[Textfield & Textarea] Counter

### ISSUE THREAD

**Issue by jeremie-lucca** [LuccaSA/lucca-front#2219]
![Capture d’écran 2023-08-22 à 15 12 43](https://github.com/LuccaSA/lucca-front/assets/25581936/ac0cfc64-3630-4ca7-ad87-6be3d6485e1e)

We need to cover Textfield & Textarea counter on `form-field` side.
A few detail must be discussed with design (typing behaviors, digits colors over defined percentage, etc.)

**Comment by vvalentin-lucca** [comment]
An example of implementation here: https://codepen.io/vincent-valentin/pen/wvNLLgO/6c53ceb8e635370cbf6060cc66316cfc
