### ISSUE TITLE
[Button] - box-shadow color issue on disabled buttons with palette-error and mod-outlined

### ISSUE THREAD

**Issue by nsarradin** [LuccaSA/lucca-front#2222]
On LF16.2.7 when a button is disabled and has `.palette-error` and `.mod-outlined `classes, render is incorrect.
The box-shadow has a red color instead of a grey color
![Capture d’écran 2023-08-22 à 15 54 22](https://github.com/LuccaSA/lucca-front/assets/9743935/0ccc7736-1560-48b2-b048-9d888506de43)

**Comment by jeremie-lucca** [comment]
It's reproductible on last published version but not locally with rc. It may be already fixed.
