### ISSUE TITLE
Support readonly typing

### ISSUE THREAD

**Issue by g-drouard** [LuccaSA/lucca-front#2249]
Currently the inputs sent to the various lucca-front components and tools don't accept readonly typing.

![image](https://github.com/LuccaSA/lucca-front/assets/15925617/e943fc5b-eee6-4e9b-9a00-2b74a1c59d3d)

**Comment by Supamiu** [comment]
Forgot to link in commit so here it is: https://github.com/LuccaSA/lucca-front/commit/05a404a1b87b925cf417613bf88ddc97eafa6090
