### ISSUE TITLE
[LuSimpleSelect] Problème d'option avec les valeurs d'enum à 0

### ISSUE THREAD

**Issue by DavidBenazra** [LuccaSA/lucca-front#2253]
Lorsque l'on passe un tableau d'options basé sur une enum utilisant des numbers du type: 
![image](https://github.com/LuccaSA/lucca-front/assets/105704633/b9663480-93e5-4343-89e6-6faa288b21eb)

L'option liée à la valeur d'enum 0 n'est pas correctement interprétée et nous laisse une entrée vide dans les options
![image](https://github.com/LuccaSA/lucca-front/assets/105704633/c6f6ac28-a3d7-4b6b-a1a2-1efc6eda33a0)

**Comment by Supamiu** [comment]
Je ferme car le problème de création d'options avec une valeur `nullable` est fixé dans la dernière release, en l'absence d'un template de reproduction de l'issue, je ne peux que le supposer (mais ça semble réaliste) mais le bug semble être réglé.
