### ISSUE TITLE
lu-input-clearer inside a callout : wrong color

### ISSUE THREAD

**Issue by BertrandPodevin** [LuccaSA/lucca-front#2257]
The callout component force link color to grey for his content. This has side effect if said content contains an input with a clearer.

![image](https://github.com/LuccaSA/lucca-front/assets/65592565/675c4040-eb5b-4b6a-953d-acaa1512a6a9)

**Comment by jeremie-lucca** [comment]
@BertrandPodevin Can you confirm that cross icon is overrided by callout's `a,.link` declaration?
