### ISSUE TITLE
[Popover] Add documentation on Prisme

### ISSUE THREAD

**Issue by AlexiaAlarza** [LuccaSA/lucca-front#2268]
On Prisme we don't see the options we can trigger with [Popover component](https://prisme.lucca.io/94310e217/p/7693f3-popover) like in tooltip page

![Capture d’écran 2023-09-07 à 10 58 47](https://github.com/LuccaSA/lucca-front/assets/77682210/28b8852d-d8fa-4d84-a759-35d7d8f01b54)

**TOOLTIP PAGE**
![Capture d’écran 2023-09-07 à 10 59 42](https://github.com/LuccaSA/lucca-front/assets/77682210/e83ec743-e612-4167-bffd-4a88b6ba9886)

**Comment by jeremie-lucca** [comment]
Replaced by new popover
