### ISSUE TITLE
[Select] mod-S / numericBadge position 

### ISSUE THREAD

**Issue by jeremie-lucca** [LuccaSA/lucca-front#2348]
`numericBadge` has position issue when used in a `select` / `mod-S`
![image](https://github.com/LuccaSA/lucca-front/assets/25581936/8ba56222-b776-45ba-b71f-97545958472e)

**Comment by vvalentin-lucca** [comment]
I can't reproduce.

Captures on Edge, Safari, Chrome and Firefox:
![Capture d’écran 2024-07-12 à 09 55 36](https://github.com/user-attachments/assets/ea1cddc3-b201-4e9b-8194-e8ea722f7b44)
![Capture d’écran 2024-07-12 à 10 17 13](https://github.com/user-attachments/assets/ae67ca11-b8ea-426f-921f-dd4788c7e102)
![Capture d’écran 2024-07-12 à 09 56 21](https://github.com/user-attachments/assets/8cbee326-cd51-44d4-b28b-1a06b6131d62)
![Capture d’écran 2024-07-12 à 09 55 45](https://github.com/user-attachments/assets/0dcd2e71-338f-4f29-9c83-2df9b9202d9e)

**Comment by jeremie-lucca** [comment]
It's related to `luSelect` with a custom displayer. Imho it's dangerous to edit our deprecated select with all side effects we know... and as we already provide Multi Select I'd rather to suggest teams to upgrade.
(So I'm closing it and I'll reopen if needed)
