### ISSUE TITLE
[Icons] Search icons are a bit cut

### ISSUE THREAD

**Issue by nsarradin** [LuccaSA/lucca-front#2382]
The search icons are all a bit cut on the top and on the right

<img width="672" alt="Capture d’écran 2023-10-27 à 14 19 22" src="https://github.com/LuccaSA/lucca-front/assets/9743935/0c7ec127-6a4b-4f67-8f22-895e03bfdfc3">
<img width="743" alt="Capture d’écran 2023-10-27 à 14 19 51" src="https://github.com/LuccaSA/lucca-front/assets/9743935/5cfa677a-38da-4dcd-b0e1-79b7027a66ea">
<img width="512" alt="Capture d’écran 2023-10-27 à 14 19 54" src="https://github.com/LuccaSA/lucca-front/assets/9743935/cad1d045-73a8-482f-95d4-e599d9fb6f90">
<img width="559" alt="Capture d’écran 2023-10-27 à 14 19 59" src="https://github.com/LuccaSA/lucca-front/assets/9743935/d3543780-c980-4c24-92dd-f119fb8dd798">

**Comment by vvalentin-lucca** [comment]
It's visible at 200% zoom, with chrome and on a retina screen.
