### ISSUE TITLE
[Select] - Overflow ellipsis is broken

### ISSUE THREAD

**Issue by nsarradin** [LuccaSA/lucca-front#2397]
In Select Simple, Department select and Establisment select components, when the option selected comes with a long text, this text is not ellipsed : 

<img width="541" alt="Capture d’écran 2023-11-02 à 15 52 18" src="https://github.com/LuccaSA/lucca-front/assets/9743935/35225f0e-2475-4507-ab7c-6bf874d91360">
<img width="542" alt="Capture d’écran 2023-11-02 à 15 56 23" src="https://github.com/LuccaSA/lucca-front/assets/9743935/15adc1c0-72f5-4989-9fad-0e1e98e9dd54">
<img width="485" alt="Capture d’écran 2023-11-02 à 15 56 58" src="https://github.com/LuccaSA/lucca-front/assets/9743935/dcd2555f-fb9a-42d9-be20-c7f6a3fb908d">

**Comment by jeremie-lucca** [comment]
Should be fixed by https://github.com/LuccaSA/lucca-front/pull/2395
