### ISSUE TITLE
[User Select] Make "getMe" optional

### ISSUE THREAD

**Issue by Nurovek** [LuccaSA/lucca-front#2422]
In some occurrences, it is not useful to have a "Me" user in a user select. 
For instance, in Engagement, when I want to retrieve Blooms I've sent to a user, I don't want to be able to select myself, as I can't send a Bloom to myself (in addition to being quite egocentric). 

Right now, the only way to do so is to override it to return EMPTY
```ts 
@Injectable()
export class UsersServiceWithoutMe extends LuUserV3Service {
  public override getMe(): Observable<ILuUser> {
    return EMPTY;
  }
}
```

So it could be nice for `<lu-user-select>` to have a "displayUserMe" boolean input to achieve this:
![user-select](https://github.com/LuccaSA/lucca-front/assets/5867791/9237d15c-4948-4e28-a012-2599097ec9d8)

without hacking stuff.

**Comment by Nurovek** [comment]
Just browsed issues quickly and I've stumbled accross this #2134, which I seem to duplicate with mine.

**Comment by jeremie-lucca** [comment]
Duplicate, but I keep this one as the issue is well described ✌️
