### ISSUE TITLE
[Text field] New input to toggle password visibility

### ISSUE THREAD

**Issue by julpellat** [LuccaSA/lucca-front#2423]
Add a new input to add a icon to toggle pasword visibility

![284321456-b99dd55e-6794-4c39-965c-c7931b49be74](https://github.com/LuccaSA/lucca-front/assets/121954131/711a37e2-3154-45a3-bf3c-6af063ebc65d)

**Comment by jeremie-lucca** [comment]
https://github.com/LuccaSA/lucca-front/pull/2434
