### ISSUE TITLE
[luSelect] mod-multiple overflow

### ISSUE THREAD

**Issue by jeremie-lucca** [LuccaSA/lucca-front#2474]
With mod-multiple, if only one long option is selected, this value can overflow in displayer.

![Capture d’écran 2023-12-28 à 11 31 09](https://github.com/LuccaSA/lucca-front/assets/25581936/2db484ef-8373-4844-8437-337db48a2993)

**Comment by vvalentin-lucca** [comment]
Solution envisaged: propose to put chips in the displayer and add a `min-width: 0` on it.

![Capture d’écran 2024-07-09 à 12 06 51](https://github.com/LuccaSA/lucca-front/assets/64789527/5041bb6a-d5fc-40cb-b250-67692cc41a98)

**Comment by jeremie-lucca** [comment]
Seems out of guidelines to use a multi select with a basic text as a result. 
Count displayer with a single tag would fix the issue.
