### ISSUE TITLE
Allow html for empty state descriptions?

### ISSUE THREAD

**Issue by vvalentin-lucca** [LuccaSA/lucca-front#2533]
(It concerns the Angular component.)

To pass a link, an emphasis or simply a line break, for example.

**Comment by Supamiu** [comment]
It's already implemented 🙂 

https://github.com/LuccaSA/lucca-front/blob/rc/packages/ng/empty-state/empty-state-page/empty-state-page.component.ts#L64

A `PortalContent` can be either a `string` or a `TemplateRef`, meaning that, to embed html, you can use ng-template, like this (I'm using page in example but it's also possible for section):

```angular2html
<lu-empty-state-page [description]="#myDescription">
  <ng-template #myDescription>
    Hey ! I'm a description with a <a href="example.com">link</a>
  </ng-template>
</lu-empty-state-page>
```

**Comment by vvalentin-lucca** [comment]
I had indeed forgotten to close this ticket! Thanks for the reply.
