### ISSUE TITLE
[Simple / Multi Select] Space should select option

### ISSUE THREAD

**Issue by jeremie-lucca** [LuccaSA/lucca-front#2552]
Pressing `space` should select the highlighted issue instead of adding a space character in search input.

https://github.com/LuccaSA/lucca-front/assets/25581936/3e90693b-4c2d-455c-9a78-90819d34dab8

**Comment by Supamiu** [comment]
Are we sure about that? What if I wanted to input `Haricots v`, with a space inside of the input?

**Comment by vvalentin-lucca** [comment]
This behavior is found in Chrome but not in Firefox, for example.

However, even with Chrome, it analyzes typing speed to determine whether you're searching for a string with a space or validating an option with a space.

**Comment by jeremie-lucca** [comment]
We fixed it and reverted as it's Chrome specific with extra typing analysis as described by @vvalentin-lucca 
It leaded to selections mistakes related while searching.
