### ISSUE TITLE
[New Select] - Chevron overflows on small-width's selects in FF

### ISSUE THREAD

**Issue by nsarradin** [LuccaSA/lucca-front#2566]
In FF browser, the select chevron arrow icon overflows as the select's width decreases

Visible on new Simple and Multiple selects

<img width="444" alt="Capture d’écran 2024-02-14 à 15 53 33" src="https://github.com/LuccaSA/lucca-front/assets/9743935/c59e3ea9-b89a-40f5-8dc9-abdfde73ad66">
<img width="281" alt="Capture d’écran 2024-02-14 à 15 53 38" src="https://github.com/LuccaSA/lucca-front/assets/9743935/b7c8b018-c2b8-4245-97e0-1493053cab3c">

**Comment by BertrandPodevin** [comment]
Can be solved with `min-width="0"` on `.simpleSelect-input`
