### ISSUE TITLE
[Empty state section] Improve spacings

### ISSUE THREAD

**Issue by jeremie-lucca** [LuccaSA/lucca-front#2622]
Spacing between description and free content (`emptyState-actions`) is handled by `<p>` default spacing, which cannot be edited as part of our component and can lead to extra spacing on component's bottom when free content is not provided. 
A better approach would be to remove this spacing, add it on `emptyState-actions`, and remove `emptyState-actions` from DOM when free content is not provided.
![capture_d___e__cran_2024-03-04_a___11 30 32](https://github.com/LuccaSA/lucca-front/assets/25581936/2d880c1c-b2a1-48be-8fc2-8d21d87093ef)

**Comment by fbasmaison-lucca** [comment]
Fixed in #2774?
