### ISSUE TITLE
[lu-number-field] New Angular component

### ISSUE THREAD

**Issue by jeremie-lucca** [LuccaSA/lucca-front#2662]
As `lu-text-input` receive more and more options related to `type="number"`, we plan to create a dedicated `lu-number-field` with multiple related options : `min`, `max` & `step`.

Providing a dedicated Angular component seems a good idea to avoid adding deprecated inputs in the short run.

**Comment by Supamiu** [comment]
First implementation in https://github.com/LuccaSA/lucca-front/commit/b3dd97114985806e6054a87b337eb9b1dffc05d4
