### ISSUE TITLE
[New Select & Dialog] Viewport overflow

### ISSUE THREAD

**Issue by jeremie-lucca** [LuccaSA/lucca-front#2667]
When a Select is included in a luModal, the dropdown position doesn't seem to be calculated, resulting to viewport overflow and unaccessible values. 

Screenshot: `LF17.3.6` / `lu-multiple-select` / `LuModal`
![CleanShot 2024-03-20 at 16 32 32@2x (1)](https://github.com/LuccaSA/lucca-front/assets/25581936/998ae543-bef2-40a7-bdf4-bb0f7ee52ef9)

Can be reproduced on https://demoprem1.ilucca.net/remuneration/salaryreviews > _Créer une campagne_ > pick _lucca france_

Bonus: Update Selects dropdown size on viewport resize.

**Comment by Supamiu** [comment]
Where can I see the source code of the example? I don't seem to reproduce in a story environment.
