### ISSUE TITLE
[Select multi] Counter displayer as parameter

### ISSUE THREAD

**Issue by jeremie-lucca** [LuccaSA/lucca-front#2671]
![image](https://github.com/LuccaSA/lucca-front/assets/25581936/81054abe-3035-4749-8179-4b1c0752faa3)

This displayer is used in a lot of cases. Having a parameter to cover this display would be a great help.

Maybe a `displayer="counter"` ?

**Comment by Supamiu** [comment]
I'm thinking about making this a directive rather than an input, to keep this logic entirely separate from base select, just like we did for many other "ready to be used" select features (API directives for instance).
