### ISSUE TITLE
[Navside] Fix numeric badge color in compact mode

### ISSUE THREAD

**Issue by martincadoux** [LuccaSA/lucca-front#2680]
![Capture d’écran 2024-03-26 à 15 56 28](https://github.com/LuccaSA/lucca-front/assets/8641352/dd29f633-ff17-4998-8442-e5f6a42ae384)

In compact mode, the numeric badge still uses the product palette instead of the brand palette.

**Comment by jeremie-lucca** [comment]
https://github.com/LuccaSA/lucca-front/pull/2681
