### ISSUE TITLE
[Empty States] Make description and title optional

### ISSUE THREAD

**Issue by Supamiu** [LuccaSA/lucca-front#2744]
## Problem

In some empty states, we may want just a `description` or just a `title`, but at the moment, both of them are required, which means we end up with one of them still present inside the DOM but empty, with all the style applied to it (use case described by @fbasmaison-lucca)

## Possible solutions

The ideal solution would be to have "at least one of them required" but that's not possible with the current tooling that Angular exposes regarding Inputs. Our solution would be to make both of them optional and rely on devs to see that if they don't provide any, well the component is empty and makes no sense.

**Comment by fbasmaison-lucca** [comment]
The solution I chose in CSS so far is to use `:empty` and hide them.

```
%hide-empty {
  &:empty {
    display: none;
  }
}

.emptyState-content-heading {
  […]
  @extend %hide-empty;
  […]
}

.emptyState-actions,
.emptyState-content-text p {
  @extend %hide-empty;
}
```

**Comment by fbasmaison-lucca** [comment]
Est-ce que ce serait pertinent d'avoir un reset de la marge inférieure sur le paragraphe, et l’appliquer sur le wrapper des boutons s’ils existent à la place. Cela permettrait de : 

* ne pas avoir besoin de surcharger le composant pour supprimer la marge superflue s'il n’y a pas d’actions,
* ne pas avoir à ajouter une marge pour écarter les boutons s’il n’y a pas de description.

Quelque chose comme ceci ?

```scss
.emptyState-content-description {
  margin-bottom: 0;
}

* + .emptyState-actions {
  margin-top: var(--pr-t-spacings-200);
}
```
