### ISSUE TITLE
[Textarea] Add support for the `rows` attribute

### ISSUE THREAD

**Issue by martincadoux** [LuccaSA/lucca-front#2752]
The **textarea** Angular component currently has a fixed height equivalent to three rows of text.

Would it be possible to let us add the `rows` attribute (via a `[rows]` input for instance), and let the textarea natively size itself based on its value instead of a fixed height?

Alternatively, we could use a custom property instead of a fixed value to set the height of the textarea:

```
--components-textfield-rows: 3;

  .textField-input-value:is(textarea) {
    height: calc(var(--components-textfield-rows) * 1lh + var(--component-textField-padding) * 2);
  }
```

**Comment by Supamiu** [comment]
iirc I originally had that and @vvalentin-lucca had a reason to not have it that I don't remember, might be worth checking with him once he's back 🙂

**Comment by vvalentin-lucca** [comment]
We had effectively concluded that the parameter was not mandator.

However, if you want to be able to easily scale a textarea in height, it's a good idea to set it so that scaling takes place automatically!

(Note: check for the presence of a min-height on the textarea.)
