### ISSUE TITLE
[Icon] chartLevels icon's schematics mapping is incorrect

### ISSUE THREAD

**Issue by martincadoux** [LuccaSA/lucca-front#2760]
The new `chartLevels` icon is incorrectly marked as deprecated and replaced with the `chartHorizontalBar` icon by the **new-icons** schematics.

This mapping should be removed, as well as any other incorrect mapping.

**Comment by jeremie-lucca** [comment]
Fixed https://github.com/LuccaSA/lucca-front/pull/2765
