### ISSUE TITLE
[Select] On Firefox, counter displayer don't display clue when already selected elements

### ISSUE THREAD

**Issue by JeanBeaurepaire** [LuccaSA/lucca-front#2834]
When I'm on Firefox with already selected elements on my multi-select, when I search other elements, clue don't display on input.

![firefox_bWEe97IjWZ](https://github.com/LuccaSA/lucca-front/assets/7081782/1ac9f93a-d04a-4c6d-b40f-3325b26a4948)

**Comment by jeremie-lucca** [comment]
This one is also related to Firefox ESR a `:has` usage.
https://github.com/LuccaSA/lucca-front/issues/2846#issuecomment-2188912052
It should be fixed on next ESR Firefox release.
