### ISSUE TITLE
[Checkbox new] Firefox ESR display checkbox under label

### ISSUE THREAD

**Issue by JeanBeaurepaire** [LuccaSA/lucca-front#2846]
Replicated on Firefox ESR 115.11.0esr on prisme 
![image](https://github.com/LuccaSA/lucca-front/assets/7081782/150955e8-501d-47fb-99dd-431772e12534)

**Comment by jeremie-lucca** [comment]
The issue is due to the usage of `:has` which is not yet covered by firefox ESR.
As it's related to Firefox ESR, which is going to be updated july 9, it seems too short to release a fix and deploy it on our apps. We suggest to wait a couple of weeks and update Firefox ESR.
