### ISSUE TITLE
[Phone number] New Angular component

### ISSUE THREAD

**Issue by jeremie-lucca** [LuccaSA/lucca-front#2882]
![image](https://github.com/LuccaSA/lucca-front/assets/25581936/1728ea1c-1395-4a66-a34a-774ade46c83f)

- Phone number component should be named `lu-phone-number-input` and use `luInput`
- It must usable in a form field (including label, tooltip, inline message, inline message state generic options), with this basic structure:
```
<lu-form-field>
  <lu-phone-number-input></lu-phone-number-input>
</lu-form-field>
```
- `lu-phone-number-input` will handle specific options
- It should be build around 2 existing inputs (Select Simple & Textfield)
- It's possible to switch from indicator selector (Simple select) to phone number (Textfield) with tab

https://www.figma.com/design/PQEOcUF9CYfKNqaejAGLWP/Lucca-components?m=auto&node-id=18201-510&t=yfoiT0Aiqf9aKYwN-1

Crafted by Cleemy

**Comment by Supamiu** [comment]
Details added with the meeting on that topic:

- https://catamphetamine.gitlab.io/libphonenumber-js/ for formatting
- We'll have to expose the formatting lib in a service (or pipe) so it can be used in a possible display only
- Format number using libphonenumber-js on blur
- Update select's country as the user types
