### ISSUE TITLE
[Simple select] When using directive (eg users/establishments), diacritics are badly escaped

### ISSUE THREAD

**Issue by Nurovek** [LuccaSA/lucca-front#2903]
When using a simple-select with, for instance, a `users` directive to feed it, and trying to search with a clue containing diacritics, the queryParam for clue seems to have been url encoded twice

e.g I want to type "Hélène" 
`http://localhost:4200/api/v3/users/search?fields=id,firstName,lastName,picture.href&clue=h%25C3%25A9l%25C3%25A8ne&paging=0,20`
![image](https://github.com/LuccaSA/lucca-front/assets/5867791/2403e8fb-7664-4068-bde5-46163880bda3)

Instead of having h%C3%A9l%C3%A8ne, we have the above badly-formatted string.

I have to type "Helene" in the clue box in order to retrieve this user.
![image](https://github.com/LuccaSA/lucca-front/assets/5867791/005a4bf3-6fd5-4ac3-976f-bb214c7eebf5)

Is this something to fix lucca-front side ? Or is it intended to be overridden app by app without sanitizing it (the `sanitizeClueFilter` function)?

**Comment by bastienguillon** [comment]
Some teams have fixed this behavior by decoding the `clue` returned by the `lu-simple-select` : [example](https://github.com/LuccaSA/Lucca.Home/blob/5294717e73835089a27c20862c9b876df3c2a66b/front/projects/home/src/app/pages/home/components/users/directives/home-user-select.directive.ts#L26). I don't think this behavior is intended

**Comment by GuillaumeNury** [comment]
Damn, we are encoding it twice:
![image](https://github.com/LuccaSA/lucca-front/assets/12662533/78bc706b-d422-476f-ab83-8f9d2ff5f0ed)

Flavien is on it

**Comment by Supamiu** [comment]
While fixing this, I noticed that we're also doing a `split(' ').join(',')`, effectively replacing space characters with commas, is that something we need to keep for the API calls? I'll assume yes for now.
