### ISSUE TITLE
[Date Select] Style issue when using with FormField component 

### ISSUE THREAD

**Issue by lmullot** [LuccaSA/lucca-front#3013]
## Description 
When using DateSelect with FormField, the rendering of the component seems to be broken (no radius, no red border on error, ...)

```html
 <lu-form-field
    label="label"
    [errorInlineMessage]="'required'"
  >
    <lu-date-select
      class="textfield-input"
      [formControlName]="'startDate'"
    />
  </lu-form-field>
```

![image](https://github.com/user-attachments/assets/3ba8cfd4-65dc-4c1d-9603-36e9055be360)

**Comment by jeremie-lucca** [comment]
Yep, Date Select is still on the old field format and is not compatible yet with FormField. 
I close the fix issue as it's in our roadmap.
