### ISSUE TITLE
[Popover2] Make close button optional

### ISSUE THREAD

**Issue by jeremie-lucca** [LuccaSA/lucca-front#3017]
![image](https://github.com/user-attachments/assets/74b61c76-81fa-4e65-9ff9-70ef2bde1ac2)

We get feedback about our close button that add friction in some contexts (like forms) and after discussions we decided to make it optional (available by default). 
It should be disabled on new Multi Language component.

**Comment by Supamiu** [comment]
Closed by https://github.com/LuccaSA/lucca-front/pull/3027
