### ISSUE TITLE
z-index conflict between Lucca Banner and cdk-overlay-container

### ISSUE THREAD

**Issue by BertrandPodevin** [LuccaSA/lucca-front#3138]
Lucca Banner `z-index` is `9000` while `cdk-overlay-container` z-index is `1000`

When using a `dialog`, if the content is high enough, it goes underneath banner wich is not cool !

![Image](https://github.com/user-attachments/assets/63aab753-7aa0-427b-9904-5dc1c36026cc)

**Comment by vvalentin-lucca** [comment]
`.cdk-overlay-container` now has a `z-index: 9999`
