### ISSUE TITLE
select + displayer - tooltip

### ISSUE THREAD

**Issue by lucienbertin** [LuccaSA/lucca-front#382]
when the value displayed by the select is too long, it wopuld be great to have a tooltip allowing us to see the full value

![image](https://user-images.githubusercontent.com/10089239/45035754-00660a80-b05b-11e8-97b6-0b9167ae4dc4.png)

**Comment by jeremie-lucca** [comment]
wont fix cuz we cant modify all selects for that, if you want to display long values, use mod-long on the textfield
