### ISSUE TITLE
i18n and locale support

### ISSUE THREAD

**Issue by lucienbertin** [LuccaSA/lucca-front#416]
this one is most certainly gonna be breaking change

**Comment by lucienbertin** [comment]
we need a way to tackel locale.

# 1st approach

reverse engineer how angular uses i18n with all their shenanigans to allow for this kind of target

```
ng serve --configuration=fr
```

https://angular.io/guide/i18n

# 2nd approach

have something similar to ng-materail, where each component uses a provided map of translate values, while allowing the user to use different 

➕ no new dependency
➕ 1 provider per component (SRP forever)
➖ its not dynamic - you have to provide the right locale before the component gets drawn, it wont be refreshed after a local change (a solution is to have a locale guard in yur router)

# 3rd approach

most (if not all) teams use ngx-translate to handle their translations, so we could use it too.

➕ dynamic change of the locale
➖ adds a new dependency

**Comment by lucienbertin** [comment]
as @Oxthan showed in IDontRemeberThePRNumber, locale can be asynchronously initialized during angular spa bootstrap, so it is possible top provide the _right_ `LOCALE_ID` even if you have to get it from somewhere asynchronously.

as a result i dont think lf i18n support will support dynamic locale change

**Comment by Oxthan** [comment]
#9638 ?

**Comment by lucienbertin** [comment]
released in 3.0
