### ISSUE TITLE
add forgroups option operator

### ISSUE THREAD

**Issue by lucienbertin** [LuccaSA/lucca-front#527]
add option operator that allows grouping

its possible to just [yoink](https://www.urbandictionary.com/define.php?term=Yoink) what @bebelz [did](https://github.com/LuccaSA/ilucca/blob/FI.rc.Reports/static/figgo/src/app/areas/reporting/columns-picker/columns-selector/custom-columns-selector/for-group.directive.ts)

**Comment by jeremie-lucca** [comment]
We need that!

**Comment by bebelz** [comment]
Lien à jour car la branche n'existe plus : https://github.com/LuccaSA/ilucca/blob/master/static/figgo/src/app/areas/reporting/columns-picker/columns-selector/custom-columns-selector/for-group.directive.ts
