### ISSUE TITLE
Cannot read property 'scrollTop' of null

### ISSUE THREAD

**Issue by maxmg** [LuccaSA/lucca-front#568]
https://github.com/LuccaSA/lucca-front/blob/07406079bc45581f272e98f4ff0f094dcf3662d4/packages/ng/libraries/core/src/lib/option/picker/option-picker.component.ts#L182

If view is rendering, native element can be null, and this error shows up.
![image](https://user-images.githubusercontent.com/6932245/52781837-d8d58e00-304d-11e9-8b34-bc132fccec73.png)

**Comment by lucienbertin** [comment]
does it still happen on latest release (2.3.1) ? i remember fixing something like that in the past

updating from 2.0 to 2.3 should be painless, if it's not let me know

**Comment by maxmg** [comment]
bug still occurs with 2.3.5
![image](https://user-images.githubusercontent.com/6932245/53738568-d1a4e180-3e8f-11e9-9c22-f2561aecc9f4.png)
