### ISSUE TITLE
[naming] use kebab case for theming components names

### ISSUE THREAD

**Issue by jeremie-lucca** [LuccaSA/lucca-front#597]

**Comment by lucienbertin** [comment]
i was wrong on that, i thougt we used kebabcase every where but we use pascal case for component key in map
- [navSide](https://github.com/LuccaSA/lucca-front/blob/master/packages/scss/src/theming/components/_nav-side.theme.scss#L63)
- [contentSection](https://github.com/LuccaSA/lucca-front/blob/master/packages/scss/src/theming/components/_content-section.theme.scss#L5)
