### ISSUE TITLE
Add pipe to remove diacritics

### ISSUE THREAD

**Issue by bastienguillon** [LuccaSA/lucca-front#641]
Add an equivalent to the `luifStripAccents` filter from lucca-ui (https://github.com/LuccaSA/lucca-ui/blob/2d462730e7f4dd216ec77c2c16ee8627c0203275/ts/filters/strip-accents.ts#L97)

**Comment by sanlucca** [comment]
Why do you need this ? Our pipes are made just to manage a specific display, not to manipulate/transform data. If its needed to persist a modified piece of data or to write a link, it should rather be a service.

**Comment by bastienguillon** [comment]
It doesn't have to be a pipe, a simple helper method would be enough ([example](https://github.com/LuccaSA/Bulp.Core.Front/blob/master/projects/search/src/lib/utils/strip-accents.ts)).

Stripping accents is something we commonly do in our search inputs. Sometimes we forget to do it though, which is not ideal. I think adding this feature would help to create better search inputs across all out applications

**Comment by sanlucca** [comment]
Upon discussion with @lucienbertin, we are wondering if accent incensitivity shouldn't be handled by our search API rather than implementing it in such helper. That way, the front doesn't have to wonder wether it should be accent sensitive or not, the search API would know better.

**Comment by bastienguillon** [comment]
If the frontend has already retrieved all the collection, an API call isn't necessary to search through the items
