### ISSUE TITLE
[luModale] Add a synchronous mode

### ISSUE THREAD

**Issue by GuillaumeNury** [LuccaSA/lucca-front#740]
When using a modale that does not trigger any requests. Classes `is-loading`, `is-error` and `is-success` are not relevant.

**Comment by lucienbertin** [comment]
i was thinking 2 things about that

1.  allow `submitAction` to be `() => Obs<T> | T` and then apply the async ux stuff only when i'm dealing with an observable
2. add a `closeDelay` parameter to replace the hardcoded .5s between the moment the submitAction finishes and the modal closes

depending on my workload it'll come in 3.1 at the beginning of september or in 3.2 a month later
