### ISSUE TITLE
lf/ng tree shakable

### ISSUE THREAD

**Issue by lucienbertin** [LuccaSA/lucca-front#787]
while running a `ng build --prod --stats-json` on another project i saw that lf ng comes full size in the chunks using it, even if you're only using a tiny chunk of it

it'll would be good for optimization purpose to have the possibility to only import selective chunks of the lib, a la angular material, i.e.

```ts
// tiny import
import { LuSelectModule } from '@lucca-front/ng/select';
// instead of
import { LuSelectModule } from '@lucca-front/ng';
```

**Comment by GuillaumeNury** [comment]
Angular material did that in version 8 (with an automatic updater thant change all paths ❤️)
