### ISSUE TITLE
formly - validation message

### ISSUE THREAD

**Issue by t8g** [LuccaSA/lucca-front#799]
it dont work or not well

**Comment by lucienbertin** [comment]
as of now the `error` wrapper is only added if your field has validators ([code](https://github.com/LuccaSA/lucca-front/blob/master/packages/ng/libraries/formly/src/lib/wrappers/error.ts#L57))

```ts
			if (field && field.validators) {
				return 'error';
			}
```
so you must have this type of config

```ts
{
  key: 'xxx',
  type: 'yyy',
  templateOptions: { /* ... */ },
  validators: [],
}
```
for the error wrapper to appear
