### ISSUE TITLE
use the new fandangled sass module stuff

### ISSUE THREAD

**Issue by lucienbertin** [LuccaSA/lucca-front#821]
[fandangled](https://www.urbandictionary.com/define.php?term=Fandangled) - fancy or special

the sass module stuff is this thingy - https://css-tricks.com/introducing-sass-modules/

**Comment by lucienbertin** [comment]
target : version 5.0

**Comment by lucienbertin** [comment]
it might have a lot of breaking changes, also we must be on the latest version of dart-sass and the figgo spa will _not_ like that cuz their mega SPA uses lucca-ui _and_ lucca-front

**Comment by jeremie-lucca** [comment]
Achieved
