### ISSUE TITLE
[modal] listen to special keyboard event (ENTER) to close with the principal action.

### ISSUE THREAD

**Issue by t8g** [LuccaSA/lucca-front#883]
For now, the `Enter` key close the modal (same behavior as `Esc` key).
It could be great to optionaly decide to bind this key (or another) to the main action of the modal.

**Comment by lucienbertin** [comment]
in fact the `enter` activates the focised dom element, which is the `x` button on top right corner

i'll add an option (in ILuModalOption) to focus the primary button on open
