### ISSUE TITLE
Format strike icon

### ISSUE THREAD

**Issue by bastienguillon** [LuccaSA/lucca-front#889]
The icons package contains icons for almost all the classic formats (`format_bold`, `format_italic`, `format_underlined`, etc), but the `format_strike` icon seems to be missing

![image](https://user-images.githubusercontent.com/8553617/67774683-1c4a1e00-fa5e-11e9-9281-500ee94d3c83.png)

The icon `format_clear` can (kind of) do the trick, but it's not optimal

**Comment by sanlucca** [comment]
closed by #1189
