### ISSUE TITLE
Expose panelClasses in option-pickers

### ISSUE THREAD

**Issue by GuillaumeNury** [LuccaSA/lucca-front#950]
Component `ALuOptionPickerComponent` implements `ILuPopoverPanel` witch contains `panelClasses`.
In order to customize these pickers, it would be simplier if `lu-option-picker-advanced` and `lu-option-picker` has an input `panelClasses`.

As a work around, it is possible to do:
```ts
@ViewChildren('waypointPanel') panelViewChildren: QueryList<LuOptionPickerAdvancedComponent>;

ngAfterViewInit(): void {
    this.panelViewChildren.changes
        .pipe(
            map(() => this.panelViewChildren.toArray())
        )
        .subscribe(panels => {
            panels.forEach(panel => (panel.panelClasses = 'mod-waypoint'));
        });
}
```

But it is not very convenant nor performant.

**Comment by lucienbertin** [comment]
i'll try to patch it asap in 4.0-rc
