### ISSUE TITLE
[SCSS][FIX] callout : callout icon no vertically aligned

### ISSUE THREAD

**Issue by RipripKipkip** [LuccaSA/lucca-front#959]
![image (5)](https://user-images.githubusercontent.com/30234402/74837084-fef8d280-5320-11ea-8ded-dce29efc5f74.png)

**Comment by lucienbertin** [comment]
![image](https://user-images.githubusercontent.com/10089239/74855141-93bef880-5340-11ea-8d6e-c9f9edcf27c9.png)

[> prisme](http://prisme.lucca.io/components/feedback/callouts?example=icones)

seems to be a problem with the override in this project

**Comment by RipripKipkip** [comment]
that's right ! i'm closing this issue
