### ISSUE TITLE
Proposal: IntersectionObserver support

### ISSUE THREAD

**Issue by GuillaumeNury** [LuccaSA/lucca-front#977]
Recently, I played a bit with [IntersectionObserver](https://github.com/w3c/IntersectionObserver). It is widely supported and has a polyfills for IE.

I wrapped it in a Service and in a Pipe. I think it could be intersting to put these in Lucca Front (probably inside a secondary entry-point).

# Use case

Render only what is needed !

The main usage I encountered is user's pictures in list or dashboard. 100 users lead to 100 requests even if only 10 users are visible.

Another usage could be in dashboard with many charts. This proposal could reduce TTI by focusing only on one chart.

# API

## IntersectionObserverService

```js
class IntersectionObserverService {
	public isVisible(element: Element): Observable<boolean>;
	public unregister(element: Element): void;
}
```

Simply pass any DivHTMLElement and you have an observable that emit whenever element is visible or not.

## IsVisibleDirective

```html
<div class="outer-element" *isVisible="let isVisible">
    <div class="inner-element" *ngIf="isVisible"></div>
</div>
```

`.outer-element` will always be rendered in DOM (so it can be observed). `.inner-element` will be rendered only when `.outer-element` is visible.

## IntersectionObserverConfig

When creating an `IntersectionObserver` we can pass the following object:

```js
interface IntersectionObserverInit {
    /**
      * `IntersectionObserverService.isVisible(element)` will be true whenever
      * element is inside this `root` element.
      * If left empty, the reference is the browser viewport
      */
    root?: Element | null;
    /**
      * In order to enlarge "visible" zone, it is possible to set a `rootMargin`.
      * For example, with "50%", the viewport and half viewport's height will be visible.
      * This is usefull to preload more items in order to make scrolling smoother.
      */
    rootMargin?: string;
    /**
      * Not usefull in this proposal.
      * With a threshold of [50, 100], observer will emit an event when 50% is visible then when 100% is visible.
      */
    threshold?: number | number[];
}
```

The configuration is retrieved using DI.

## VisibilityContainerDirective

Sometimes, we are not interested in whether or not element intersect with viewport. Sometime, we have a container with a fixed height. In this case, we can use `VisibilityContainerDirective`:

```html
<div class="my-container" visibilityContainer>
    <div class="outer-element" *isVisible="let isVisible">
        <div class="inner-element" *ngIf="isVisible"></div>
    </div>
</div>
```

In this case, `.inner-element` is rendered only when `.outer-element` intersect with `.my-container`.

**Comment by sanlucca** [comment]
We might add this in 2021 as we are dropping support for IE11

**Comment by GuillaumeNury** [comment]
Nice ! In the meantime, there is a polyfill (we use it in NikoNiko)

**Comment by Supamiu** [comment]
Do we want to do something with this 3 years old issue?

**Comment by GuillaumeNury** [comment]
It is more something for lucca-cdk, so we can close it
